/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package GUI;

import Banco.CuentaBancaria;
import Banco.CuentaLogic;
import javax.swing.JOptionPane;

/**
 *
 * @author fwscg
 */
public class AcountRegister extends java.awt.Dialog {

    /**
     * Creates new form AcountRegister
     */
    public AcountRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        buttonRegister.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Registro = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        nombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        curpCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        correoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        condiciones = new javax.swing.JCheckBox();
        buttonRegister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        passwordCliente = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        repetirPasswordCliente = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        usuarioCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mostrarPassword = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(46, 64, 83));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Cuenta  Bancaria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 243, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BXZ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 60, -1));

        Registro.setBackground(new java.awt.Color(255, 255, 255));
        Registro.setPreferredSize(new java.awt.Dimension(500, 630));
        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, 420, 17));

        nombreCliente.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nombreCliente.setBorder(null);
        nombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreClienteFocusLost(evt);
            }
        });
        nombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreClienteMousePressed(evt);
            }
        });
        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });
        Registro.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, 420, 26));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setText("Nombre completo");
        Registro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, 142, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, 292, 17));

        curpCliente.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        curpCliente.setBorder(null);
        curpCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curpClienteMousePressed(evt);
            }
        });
        curpCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curpClienteActionPerformed(evt);
            }
        });
        Registro.add(curpCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, 292, 26));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setText("Clave Única de Registro de Población (CURP)");
        Registro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setText("Correo");
        Registro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, 142, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 247, 292, 17));

        correoCliente.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        correoCliente.setBorder(null);
        correoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoClienteMousePressed(evt);
            }
        });
        correoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoClienteActionPerformed(evt);
            }
        });
        Registro.add(correoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 214, 292, 26));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retrato-mujer-que-trabaja-empresa-nueva-creacion_1.png"))); // NOI18N
        Registro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 160, 280));

        condiciones.setBackground(new java.awt.Color(255, 255, 255));
        condiciones.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        condiciones.setText("Acepto los términos y condiciones de uso ");
        condiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condicionesActionPerformed(evt);
            }
        });
        Registro.add(condiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        buttonRegister.setBackground(new java.awt.Color(40, 116, 166));
        buttonRegister.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setText("Registrar");
        buttonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonRegisterMouseExited(evt);
            }
        });
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        Registro.add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 100, 50));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setText("Contraseña");
        Registro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 352, 142, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 292, 17));

        passwordCliente.setToolTipText("");
        passwordCliente.setBorder(null);
        passwordCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordClienteMousePressed(evt);
            }
        });
        Registro.add(passwordCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 376, 292, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 492, -1, -1));

        repetirPasswordCliente.setToolTipText("");
        repetirPasswordCliente.setBorder(null);
        repetirPasswordCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repetirPasswordClienteMousePressed(evt);
            }
        });
        Registro.add(repetirPasswordCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 451, 292, 34));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel9.setText("Repertir contraseña");
        Registro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 427, 142, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 328, 292, 17));

        usuarioCliente.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        usuarioCliente.setBorder(null);
        usuarioCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioClienteMousePressed(evt);
            }
        });
        usuarioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioClienteActionPerformed(evt);
            }
        });
        Registro.add(usuarioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 295, 292, 26));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel10.setText("Usuario");
        Registro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 271, 142, -1));

        mostrarPassword.setBackground(new java.awt.Color(255, 255, 255));
        mostrarPassword.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        mostrarPassword.setText("Mostrar contraseña");
        mostrarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPasswordActionPerformed(evt);
            }
        });
        Registro.add(mostrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 208, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        Registro.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 403, 292, 17));

        jPanel1.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 610));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void nombreClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreClienteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteFocusGained

    private void nombreClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreClienteFocusLost

    }//GEN-LAST:event_nombreClienteFocusLost

    private void nombreClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreClienteMousePressed
        //dynamicFieldName ();
    }//GEN-LAST:event_nombreClienteMousePressed

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteActionPerformed

    private void curpClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curpClienteMousePressed
        //dynamicFieldCURP();
    }//GEN-LAST:event_curpClienteMousePressed

    private void curpClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curpClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curpClienteActionPerformed

    private void correoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoClienteMousePressed

        //dynamicFieldEmail();
    }//GEN-LAST:event_correoClienteMousePressed

    private void correoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoClienteActionPerformed

    private void condicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condicionesActionPerformed
        buttonRegister.setEnabled(true);
    }//GEN-LAST:event_condicionesActionPerformed

    private void buttonRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegisterMouseEntered
        //buttonRegister.setBackground(new java.awt.Color(52, 152, 219));
    }//GEN-LAST:event_buttonRegisterMouseEntered

    private void buttonRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegisterMouseExited
        //buttonRegister.setBackground(new java.awt.Color(40, 116, 166));
    }//GEN-LAST:event_buttonRegisterMouseExited

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        int numeroCuenta=0;
        if(!nombreCliente.getText().isEmpty()
            &&!curpCliente.getText().isEmpty()
            &&!usuarioCliente.getText().isEmpty()
            &&!correoCliente.getText().isEmpty()
            &&!passwordCliente.getText().isEmpty()
            &&repetirPasswordCliente.getText().equals(passwordCliente.getText())){
            CuentaBancaria cuentaB = new CuentaBancaria(nombreCliente.getText(), usuarioCliente.getText(), numeroCuenta, 0, curpCliente.getText(), correoCliente.getText(), passwordCliente.getText());
            if(CuentaLogic.insertar(cuentaB)){
                JOptionPane.showMessageDialog(this,"Se ha registrado satisfactoriamente");
                numeroCuenta++;
            }
            else{
                JOptionPane.showMessageDialog(this,"Usuario ya existente");
            }
        }
        else{
        JOptionPane.showMessageDialog(this,"Digite los datos");}
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void passwordClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordClienteMousePressed
        //dynamicFieldPassword();
    }//GEN-LAST:event_passwordClienteMousePressed

    private void repetirPasswordClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repetirPasswordClienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_repetirPasswordClienteMousePressed

    private void usuarioClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioClienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioClienteMousePressed

    private void usuarioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioClienteActionPerformed

    private void mostrarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPasswordActionPerformed
        if (mostrarPassword.isSelected()){
            passwordCliente.setEchoChar((char)0);
            repetirPasswordCliente.setEchoChar((char)0);
        }else{
            passwordCliente.setEchoChar('*');
            repetirPasswordCliente.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcountRegister dialog = new AcountRegister(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Registro;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JCheckBox condiciones;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JTextField curpCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JCheckBox mostrarPassword;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JPasswordField passwordCliente;
    private javax.swing.JPasswordField repetirPasswordCliente;
    private javax.swing.JTextField usuarioCliente;
    // End of variables declaration//GEN-END:variables
}
