/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CuentaBancaria;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class IniciarSecionGUI extends javax.swing.JFrame {

        static CuentaBancaria cliente;
    static boolean tarpass, tartxt = true;

    /**
     * Creates new form IniciarSecionGUI
     */
    public IniciarSecionGUI() {
        initComponents();
        setLocationRelativeTo(null);
        tarjetapss.setVisible(tarpass);
        tarjetatxt.setVisible(tartxt);
    }

    public static void TarjetaCambio() {
        if (CrearCuentaBancaria.activarTarjeta == false) {
            tarpass = false;
            tartxt = true;
        } else {
            tartxt = false;
            tarpass = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconoPersona = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nipPss = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sesionBtn = new javax.swing.JButton();
        registrarseBtn = new javax.swing.JButton();
        tarjetatxt = new javax.swing.JTextField();
        tarjetapss = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ICONOPERSON2.png"))); // NOI18N
        jPanel1.add(iconoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 510, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TARJETA BANCARIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 310, 30));

        nipPss.setForeground(new java.awt.Color(204, 204, 204));
        nipPss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nipPss.setText("CONTRASENA");
        nipPss.setBorder(null);
        nipPss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nipPssMouseClicked(evt);
            }
        });
        nipPss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nipPssKeyReleased(evt);
            }
        });
        jPanel1.add(nipPss, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 310, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NIP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 310, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 253, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 253, 30));

        sesionBtn.setText("INICIAR SESIÓN");
        sesionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sesionBtnMouseClicked(evt);
            }
        });
        jPanel1.add(sesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        registrarseBtn.setText("REGISTRARSE");
        registrarseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseBtnMouseClicked(evt);
            }
        });
        jPanel1.add(registrarseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        tarjetatxt.setEditable(false);
        tarjetatxt.setForeground(new java.awt.Color(204, 204, 204));
        tarjetatxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarjetatxt.setText("NÚMERO DE TARJETA BANCARIA");
        tarjetatxt.setBorder(null);
        jPanel1.add(tarjetatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 310, 30));

        tarjetapss.setEditable(false);
        tarjetapss.setForeground(new java.awt.Color(204, 204, 204));
        tarjetapss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarjetapss.setText("4152313982877245");
        tarjetapss.setBorder(null);
        jPanel1.add(tarjetapss, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 310, 30));

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 460));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseBtnMouseClicked
        // TODO add your handling code here:
        CrearCuentaBancaria crear = new CrearCuentaBancaria();
        crear.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarseBtnMouseClicked

    private void sesionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sesionBtnMouseClicked
        // TODO add your handling code here:

        if (CrearCuentaBancaria.activarTarjeta == false) {
            JOptionPane.showMessageDialog(null, "NO SE HA REGISTRADO AUN", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        if (CrearCuentaBancaria.activarTarjeta == true) {
            if (!"CONTRASENA".equals(String.valueOf(nipPss.getPassword())) && !"".equals(String.valueOf(nipPss.getPassword()))) {
                if (!cliente.getPassword().equals(String.valueOf(nipPss.getPassword()))) {
                    JOptionPane.showMessageDialog(null, "EL NIP ES INCORRECTO", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    OperacionesBancariaGUI operacion = new OperacionesBancariaGUI();
                    operacion.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "INGRESE EL NIP", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_sesionBtnMouseClicked

    private void nipPssKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nipPssKeyReleased
        // TODO add your handling code here:
        if ("".equals(String.valueOf(nipPss.getPassword())) || "CONTRASENA".equals(String.valueOf(nipPss.getPassword()))) {
            nipPss.setForeground(Color.GRAY);
            nipPss.setText("CONTRASENA");
        }
    }//GEN-LAST:event_nipPssKeyReleased

    private void nipPssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nipPssMouseClicked
        // TODO add your handling code here:
        if("".equals(String.valueOf(nipPss.getPassword()))){
            nipPss.setForeground(Color.GRAY);
            nipPss.setText("CONTRASENA");
        }
        if ("CONTRASENA".equals(String.valueOf(nipPss.getPassword()))) {
            nipPss.setText("");
            nipPss.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_nipPssMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSecionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSecionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSecionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSecionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSecionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconoPersona;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField nipPss;
    private javax.swing.JButton registrarseBtn;
    private javax.swing.JButton sesionBtn;
    private javax.swing.JPasswordField tarjetapss;
    private javax.swing.JTextField tarjetatxt;
    // End of variables declaration//GEN-END:variables
}
