/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CuentaBancaria;

import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class OperacionesBancariaGUI extends javax.swing.JFrame {

    static CuentaBancaria cliente;
    static int contadorMovimientos;

    /**
     * Creates new form OperacionesBancariaGUI
     */
    public OperacionesBancariaGUI() {
        initComponents();
        setLocationRelativeTo(null);
        retirarPnl.setVisible(false);
        depositarPnl.setVisible(false);

        saludo.setText("Hola, " + cliente.getNombre());
        numeroTarjeta.setText(cliente.getCuenta());
        saldo.setText("$" + String.valueOf(cliente.ConsultarSaldo()));
        movimientoRealizado.setText("Movimientos Realizados " + contadorMovimientos);
        System.out.println(historialMovimiento.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gb = new javax.swing.JPanel();
        bienvenidaPnl = new javax.swing.JPanel();
        saludo = new javax.swing.JLabel();
        saldoPnl = new javax.swing.JPanel();
        saldo = new javax.swing.JLabel();
        mensajeSaldo = new javax.swing.JLabel();
        mensajePesos = new javax.swing.JLabel();
        numeroTarjeta = new javax.swing.JLabel();
        mensajeCuenta = new javax.swing.JLabel();
        depositarBtn = new javax.swing.JButton();
        retirarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialMovimiento = new javax.swing.JTextArea();
        movimientoRealizado = new javax.swing.JLabel();
        depositarPnl = new javax.swing.JPanel();
        depositotxt = new javax.swing.JTextField();
        cancelarBtn = new javax.swing.JButton();
        ingresarBtn = new javax.swing.JButton();
        $deposito = new javax.swing.JLabel();
        mensajeDeposito = new javax.swing.JLabel();
        retirarPnl = new javax.swing.JPanel();
        $reirtar = new javax.swing.JLabel();
        retirartxt = new javax.swing.JTextField();
        reitrarBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();
        mensajeRetirar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidaPnl.setBackground(new java.awt.Color(0, 93, 139));

        saludo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        saludo.setForeground(new java.awt.Color(255, 255, 255));
        saludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saludo.setText("HOLA, ");

        javax.swing.GroupLayout bienvenidaPnlLayout = new javax.swing.GroupLayout(bienvenidaPnl);
        bienvenidaPnl.setLayout(bienvenidaPnlLayout);
        bienvenidaPnlLayout.setHorizontalGroup(
            bienvenidaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bienvenidaPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saludo, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );
        bienvenidaPnlLayout.setVerticalGroup(
            bienvenidaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bienvenidaPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saludo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        gb.add(bienvenidaPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        saldoPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        saldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mensajeSaldo.setText("Saldo disponible");
        mensajeSaldo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        mensajePesos.setText("CUENTA EN PESOS");

        numeroTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mensajeCuenta.setText("número de cuenta");

        depositarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DEPOSITAR.png"))); // NOI18N
        depositarBtn.setText("DEPOSITAR");
        depositarBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        depositarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarBtnActionPerformed(evt);
            }
        });

        retirarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RETIRAR.png"))); // NOI18N
        retirarBtn.setText("RETIRAR");
        retirarBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        retirarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBtnActionPerformed(evt);
            }
        });

        salirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR.png"))); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        historialMovimiento.setColumns(20);
        historialMovimiento.setRows(5);
        jScrollPane1.setViewportView(historialMovimiento);

        movimientoRealizado.setText("MOVIMIENTOS REALIZADOS");

        javax.swing.GroupLayout saldoPnlLayout = new javax.swing.GroupLayout(saldoPnl);
        saldoPnl.setLayout(saldoPnlLayout);
        saldoPnlLayout.setHorizontalGroup(
            saldoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saldoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajeSaldo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensajePesos)
                    .addComponent(mensajeCuenta)
                    .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(saldoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saldoPnlLayout.createSequentialGroup()
                        .addGroup(saldoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositarBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(retirarBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salirBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saldoPnlLayout.createSequentialGroup()
                        .addComponent(movimientoRealizado)
                        .addGap(51, 51, 51))))
        );
        saldoPnlLayout.setVerticalGroup(
            saldoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajePesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(saldoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(saldoPnlLayout.createSequentialGroup()
                        .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajeCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajeSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(saldoPnlLayout.createSequentialGroup()
                        .addComponent(movimientoRealizado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depositarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retirarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salirBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gb.add(saldoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 260));

        depositarPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        depositotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositotxtMouseClicked(evt);
            }
        });

        cancelarBtn.setText("CANCELAR");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        ingresarBtn.setText("INGRESAR");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });

        $deposito.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        $deposito.setText("$");

        mensajeDeposito.setText("INGRESE CANTIDAD A DEPOSITAR");

        javax.swing.GroupLayout depositarPnlLayout = new javax.swing.GroupLayout(depositarPnl);
        depositarPnl.setLayout(depositarPnlLayout);
        depositarPnlLayout.setHorizontalGroup(
            depositarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositarPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depositarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mensajeDeposito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(depositarPnlLayout.createSequentialGroup()
                        .addGroup(depositarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(depositarPnlLayout.createSequentialGroup()
                                .addComponent($deposito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depositotxt))
                            .addComponent(ingresarBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        depositarPnlLayout.setVerticalGroup(
            depositarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositarPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeDeposito)
                .addGap(10, 10, 10)
                .addGroup(depositarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent($deposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(depositarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn)
                    .addComponent(ingresarBtn))
                .addContainerGap())
        );

        gb.add(depositarPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        retirarPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        retirarPnl.setPreferredSize(new java.awt.Dimension(200, 97));

        $reirtar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        $reirtar.setText("$");

        reitrarBtn.setText("RETIRAR");
        reitrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reitrarBtnActionPerformed(evt);
            }
        });

        CancelarBtn.setText("CANCELAR");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });

        mensajeRetirar.setText("INGRESE LA CANTIDAD A RETIRAR");

        javax.swing.GroupLayout retirarPnlLayout = new javax.swing.GroupLayout(retirarPnl);
        retirarPnl.setLayout(retirarPnlLayout);
        retirarPnlLayout.setHorizontalGroup(
            retirarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retirarPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(retirarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensajeRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addGroup(retirarPnlLayout.createSequentialGroup()
                        .addComponent(reitrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelarBtn))
                    .addGroup(retirarPnlLayout.createSequentialGroup()
                        .addComponent($reirtar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retirartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        retirarPnlLayout.setVerticalGroup(
            retirarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retirarPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(retirarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent($reirtar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(retirartxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(retirarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reitrarBtn)
                    .addComponent(CancelarBtn))
                .addContainerGap())
        );

        gb.add(retirarPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gb, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositotxtMouseClicked
        // TODO add your handling code here:
        depositotxt.setText("");
    }//GEN-LAST:event_depositotxtMouseClicked

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        // TODO add your handling code here:
        if (!"0".equals(depositotxt.getText()) && !"".equals(depositotxt.getText())) {
            double deposito = Double.parseDouble(depositotxt.getText());
            if (deposito > 0) {
                historialMovimiento.setText("SE DEPSITO: $ " + deposito);
                cliente.Depositar(deposito);
                saldo.setText("$ " + String.valueOf(cliente.ConsultarSaldo()));
                contadorMovimientos++;
                movimientoRealizado.setText("Movimientos Realizados " + contadorMovimientos);
                JOptionPane.showMessageDialog(null, "SE HA INGRESADO CON EXITO!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "NO PUEDE INGRESAR CANTIDAD NEGATIVA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE UNA CANTIDAD", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        retirarPnl.setVisible(false);
        depositarPnl.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void reitrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reitrarBtnActionPerformed
        // TODO add your handling code here:
        if (!"0".equals(retirartxt.getText()) && !"".equals(retirartxt.getText())) {
            double retiro = Double.parseDouble(retirartxt.getText());
            if (retiro > 0) {
                if (cliente.ConsultarSaldo() >= retiro) {
                    historialMovimiento.setText("SE RETIRO: $ " + retiro);
                    cliente.Retirar(retiro);
                    saldo.setText("$ " + String.valueOf(cliente.ConsultarSaldo()));
                    contadorMovimientos++;
                    movimientoRealizado.setText("Movimientos Realizados " + contadorMovimientos);
                    JOptionPane.showMessageDialog(null, "SE HA RETIRADO CON EXITO!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "NO TIENES SALDO SUFICIENTE", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "NO PUEDE INGRESAR CANTIDAD NEGATIVA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE UNA CANTIDAD", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_reitrarBtnActionPerformed

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        // TODO add your handling code here:
        retirarPnl.setVisible(false);
        depositarPnl.setVisible(false);
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void retirarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBtnActionPerformed
        // TODO add your handling code here:
        depositarPnl.setVisible(false);
        retirarPnl.setVisible(true);
    }//GEN-LAST:event_retirarBtnActionPerformed

    private void depositarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarBtnActionPerformed
        // TODO add your handling code here:
        retirarPnl.setVisible(false);
        depositarPnl.setVisible(true);
    }//GEN-LAST:event_depositarBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesBancariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesBancariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesBancariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesBancariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionesBancariaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $deposito;
    private javax.swing.JLabel $reirtar;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JPanel bienvenidaPnl;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton depositarBtn;
    private javax.swing.JPanel depositarPnl;
    private javax.swing.JTextField depositotxt;
    private javax.swing.JPanel gb;
    private javax.swing.JTextArea historialMovimiento;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensajeCuenta;
    private javax.swing.JLabel mensajeDeposito;
    private javax.swing.JLabel mensajePesos;
    private javax.swing.JLabel mensajeRetirar;
    private javax.swing.JLabel mensajeSaldo;
    private javax.swing.JLabel movimientoRealizado;
    private javax.swing.JLabel numeroTarjeta;
    private javax.swing.JButton reitrarBtn;
    private javax.swing.JButton retirarBtn;
    private javax.swing.JPanel retirarPnl;
    private javax.swing.JTextField retirartxt;
    private javax.swing.JLabel saldo;
    private javax.swing.JPanel saldoPnl;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel saludo;
    // End of variables declaration//GEN-END:variables
}
